git_username: user
git_credential: env
registry_password: env
registry_namespace: registry
challenge_namespace: challenges
istio_namespace: istio-system
tcp_domain_name: ctf.psuccso.org
https_domain_name: https://ctf.psuccso.org/
certificate_issuer_name: istio-issuer
istio_ingress_name: ingressgateway
external_tcp_port: 443
external_https_port: 443
expire_interval: 3600
ctfd_url: https://ctf.psuccso.org/
