git_username: 23younesm
git_credential: erm
registry_password: erm
registry_namespace: ctfd-challenges
challenge_namespace: ctfd-challenges
tcp_domain_name: ctf.psuccso.org
https_domain_name: https://ctf.psuccso.org/
external_tcp_port: 80
external_https_port: 443
expire_interval: 3600
ctfd_url: https://ctf.psuccso.org/
